#!/usr/bin/env python3

import sys

from rqt_mypkg.SceneGenerator import SceneGenerationHMIPlugin
from rqt_gui.main import Main

plugin = 'rqt_mypkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))